# This program takes the csv file generated by the BMS QuikEval GUI and creates
# a new csv file that can be loaded into a pandas dataframe without errors

# Put each line of csv into list
#a_file = open("discharge_2cells.csv", "r")

file_name = input("Enter the file name with the .csv at the end: ")
a_file = open(file_name, "r")
lines = a_file.readlines()
a_file.close()
column_names = lines[4] # holds the column names of the table
lines = lines[6:-4] # remove first six lines and last 4 lines w/ no data

# Initialization of variables
divided_lines = [] # holder for each line seperated by list of indiv. chars.
char_list = [] # temporary placeholder for list of chars in each line
comma_count = 0 # counter for # of commas detected in line of divided_lines

# Create a list of lists of each character
for line_num in range(len(lines)):
    for char in lines[line_num]:   
        char_list.append(char)
    
    divided_lines.append(char_list)
    char_list = [] #clear the list so next list can be loaded

# Go through each char of each line and change the decimal representation format
# of each cell reading to be X.XXXX from X,XXXX
for line in range(len(divided_lines)):
    for char in range(len(divided_lines[line])):
        if divided_lines[line][char] == ',':
            comma_count += 1
            if ((comma_count >= 10) and (comma_count % 2 == 0)):
                #this if statement is to do with the fact that the first decimal
                #point comes from the 10th occurence of a comma in the line and
                #then every other instance thereafter until the end of the line
                divided_lines[line][char] = '.'
                
    comma_count = 0 #reset comma_count because the next line will be counted

# Recreate the list of lines
line = ''
lines = []
for line_num in range(len(divided_lines)):
    for char in range(len(divided_lines[line_num])):
        line += divided_lines[line_num][char]
    lines.append(line)
    line = ''


# Write the list to a new file
new_file_name = input("Enter a name for your new csv file followed by .csv: ")
f = open(new_file_name, "a")
f.write(column_names) # add the column names to the first line of file

for line in lines:
    f.write(line)

f.close()

