# This program takes the csv file generated by the BMS QuikEval GUI and creates
# a new csv file that can be loaded into a pandas dataframe without errors

from settings import Csv

### Choose file to be converted from csv to pandas data_frame
##
##dc_csv = Csv('discharge_2cells.csv')
##
##lines = dc_csv.to_lines() # split csv into list of lines
##
##divided_lines = dc_csv.to_chars(lines) # split lines into lines of chars
##
##fixed_lines = dc_csv.fix_decimals(divided_lines) # change decimals to be '.'
##
##dc_csv.write_to_file(fixed_lines) #create new cleaned file

##cardata = Csv('5cell_fullspeed.csv')
##
##lines = cardata.to_lines() # split csv into list of lines
##
##divided_lines = cardata.to_chars(lines) # split lines into lines of chars
##
##fixed_lines = cardata.fix_decimals(divided_lines) # change decimals to be '.'
##
##cardata.write_to_file(fixed_lines) #create new cleaned file

##burstdata = Csv('continuous_steering_busts.csv')
##
##lines = burstdata.to_lines() # split csv into list of lines
##
##divided_lines = burstdata.to_chars(lines) # split lines into lines of chars
##
##fixed_lines = burstdata.fix_decimals(divided_lines) # change decimals to be '.'
##
##burstdata.write_to_file(fixed_lines) #create new cleaned file

##chargedata = Csv('charging.csv')
##
##lines = chargedata.to_lines() # split csv into list of lines
##
##divided_lines = chargedata.to_chars(lines) # split lines into lines of chars
##
##fixed_lines = chargedata.fix_decimals(divided_lines) # change decimals to be '.'
##
##chargedata.write_to_file(fixed_lines) #create new cleaned file

##data4x2_1 = Csv('4x2_fullspeed.csv')
##
##lines = data4x2_1.to_lines() # split csv into list of lines
##
##divided_lines = data4x2_1.to_chars(lines) # split lines into lines of chars
##
##fixed_lines = data4x2_1.fix_decimals(divided_lines) # change decimals to be '.'
##
##data4x2_1.write_to_file(fixed_lines) #create new cleaned file
##

data4x2_1 = Csv('4x2_fullspeed+steering.csv')

lines = data4x2_1.to_lines() # split csv into list of lines

divided_lines = data4x2_1.to_chars(lines) # split lines into lines of chars

fixed_lines = data4x2_1.fix_decimals(divided_lines) # change decimals to be '.'

data4x2_1.write_to_file(fixed_lines) #create new cleaned file


